name: Deploy An Application using Checkout--->Login into ECR--->Build Image & Push it into ECR--->Deploy to Targeted Server

on:
  push:
    tags:
      - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
                  
        - name: Log into the elastic container registry(ECR)
          run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO_URL }}

        - name: Build and push the docker images to ECR registry in AWS
          run: |
            TAG=${{ github.ref_name }}
            docker build -t photography .
            docker tag photography ${{ secrets.AWS_ECR_REPO_URL }}/photography:$TAG
            docker push ${{ secrets.AWS_ECR_REPO_URL }}/photography:$TAG


